export const privacyPolicy = `
Welcome to growthbot.ng (‘the company’, ‘us’, ‘our’, ‘we’), a platform for discipleship and a real-time chat system for peer-related human disciplers. We are an innovation of the Great Commission Movement of Nigeria.

We take online privacy seriously and respect the concerns of our users. We are committed to ensuring that the information collected is securely processed and stored, in compliance with the Data Protection Act, the Nigerian Data Protection Regulation 2019 (NDPR), and other applicable laws and international privacy regulations, such as the General Data Protection Regulation (GDPR), where applicable.

This document is an electronic record generated by a computer system and does not require a physical or digital signature, as per the Nigerian Data Protection Regulation 2019, other relevant Nigerian Laws, and international conventions.

By using this application, you are consenting to the practices described in this Privacy Policy. This Privacy Policy outlines how we collect, use, and protect the personal information we collect through growthbot.ng (the "Site") and our services.

COLLECTION OF INFORMATION

We collect information at various stages of interaction with our website, including registration and subscription for services.

1.1	Registration

 We encourage you to provide accurate information on this site. To use certain features, such as connecting with a discipler, you must register as a user ("User") on the Progressive Web App (PWA), using a referral access code. The registration process may require you to provide your name, email address, phone number, and create a username and password.

We may collect additional information automatically, such as IP addresses, device types, and browsing activity, through cookies or similar technologies to improve our services and enhance functionality.

You are responsible for ensuring that your account information is accurate and kept confidential. Your account should only be used by you.

1.2	Information You Upload

1.2.1. You may choose to upload documents or other information to the PWA. While we implement measures to secure this data, you understand that any information you upload is done at your own risk. By uploading such information, you consent to it being stored on our servers.

1.2.2. We retain this information for as long as necessary to provide our services. If you delete your account, we will delete the uploaded information, subject to the following conditions: 

There may be latency in deleting information from our systems and backups.
We may retain information to comply with legal obligations, resolve disputes, or enforce agreements.

1.3. Information from Other Sources

We may collect information from third parties, such as identity verification services, support interactions, surveys, and responses to disciplinary guidance from our disciplers.

2. USE OF INFORMATION

We collect and use your personal information for the following purposes:

To deliver the services you request (e.g., providing personalized responses and guidance). 
To comply with applicable laws, regulations, or government requests. 
 To better understand your needs in relation to our services.
 To enhance our website and services. 
To communicate important updates, new features, and promotional offers (with your consent). 
To improve user experience by delivering targeted content (with your consent). 
 To address any claims or disputes related to your use of our services. 
 To ensure the security and integrity of the PWA and protect our rights. 
To identify and resolve technical issues related to the PWA and services. 
 For marketing, analysis, and promotional activities in line with applicable laws.

3. DATA SHARING AND DISCLOSURE

We may share your information with other users on the PWA on a need-to-know basis to provide you with the services you’ve selected. However, we do not share your personal information beyond this, unless required by law or as outlined in this Privacy Policy.

While we take every precaution to protect your information, we are not liable for any loss or damage arising from information shared on the PWA. You are advised to keep copies of your data stored on personal devices, as the PWA should not be used as external storage.

4. CONSENT AND WITHDRAWAL

By using the PWA and registering for our services, you consent to the terms of this Privacy Policy. If you do not agree, you may withdraw consent at any time. Note, however, that withdrawal of consent may prevent us from providing you with certain services.

 We reserve the right to modify this Privacy Policy at any time. You are responsible for reviewing it periodically. If changes are made, we will update the "last updated" date at the top of the page.

You may withdraw consent at any time by contacting us via our contact form. If you withdraw consent, we may suspend our provision of services.

If you share third-party personal information with us, you confirm that you have obtained the necessary consent to do so.

5. DATA SECURITY

We implement technical and organizational measures to protect your information, including encryption and secure access protocols. However, please note that no security system is entirely foolproof, and we cannot guarantee the absolute security of your data.

6. DATA RETENTION

We retain personal information only for as long as necessary to provide our services or as required by law. When data is no longer required, it will be securely deleted or anonymised.

7. INTERNATIONAL DATA TRANSFERS

If you are accessing this service from outside Nigeria, please be aware that your information may be transferred to and stored on servers located in countries that may have different data protection laws than your jurisdiction. By using this service, you consent to such transfers.


8. CHANGES TO THE PRIVACY POLICY

We may update this Privacy Policy to reflect changes in our practices, legal requirements, or operational needs. Significant changes will be communicated through our website or via email. The "last updated" date at the top of the page indicates the most recent update.

9. USER RIGHTS

Under applicable data protection laws, you have certain rights regarding your personal information, including the right to:

Access, correct, or delete your personal data.
Object to or restrict the processing of your data.
Withdraw consent where processing is based on consent.
Data portability (transfer your data to another service provider).
To exercise any of these rights, please contact us using the details provided in the contact section below.

Contact Us:
For any questions about this Privacy Policy or to exercise your data rights, please contact us through the contact form on our website.
`