export const tos = `
Welcome To growthbot.ng (‘the company’, ‘us’, ‘our’, ‘we’), a GrowthBot for discipleship and a real time chat system for peer-related human disciplers. We are an innovation of the Great Commission  Movement of Nigeria.  

1. TERMS OF USE  

1.1 The content of this Progressive Web App (Platform) is the property of the Great Commission  Movement of Nigeria. We provide a service that facilitates ease of access to tips for sharing the gospel  of Jesus Christ and finding and linking disciples to disciplers in identified locations, and this service  is provided in good faith. Our services are provided to bridge the gap between the disciples of Jesus  Christ and the disciplers.  

1.2 This document is an electronic record in terms of The Nigerian Data Protection Regulation 2019, other  relevant Nigerian Laws and General Data Protection Regulations, laws, conventions, and  International Convention as may be applicable in the forum jurisdiction where the site may be used.  Therefore all rules on the laws applicable to this document. This electronic record is generated by a  computer system and does not require any physical or digital signatures.  

1.3 Your use of the website services and tools are governed by the following terms and conditions (“Terms  of Use”) as applicable to the platform including the applicable policies which are incorporated herein  by way of reference. If you engage on the platform, you shall be subject to the policies that apply to  the platform for such engagement. By mere use of the platform, these terms and conditions including  the policies constitute your binding obligations, to us  

1.4 We request that you carefully go through these terms of use ("Terms of Use") before you decide to  avail our services of. By registering with the company to avail of our services, you irrevocably accept  all the obligations stipulated in these terms of use and agree to abide by them.  

1.5 Accessing the platform through any medium, including but not limited to mobile phones,  smartphones, and tablets, is also subject to these terms of use. These terms of use supersede all  previous oral and written terms and conditions (if any) communicated to you.  

1.6 By using this platform, you signify your agreement to these Terms of Use. Take note that we reserve  the right to modify the terms of use, our policies, and any services rendered by or through us without  notice and liability to you or any third party. We also have the right to terminate any portion of the  platform or the services offered by the company for any reason, without notice and liability to you or  any third party. To make sure you are aware of any changes; please review these terms of use  periodically. The website should not be used in cases of urgent needs and we do not, and should not  be considered in any form to be a substitute for clergy or a church.  

2. DEFINITIONS 

a) Disciple - any person who wishes to connect to a discipler  

b) Discipler - any person who will be linked to a disciple for discipleship  

c) Service – the access service “growthbot.ng” is provided by the Service Provider  electronically to users.  

d) Advice –  

e) Agreements – agreements for the provision of services concluded based on Terms and  Conditions  

f) User - a natural person who is at least 18 years old and has not been deprived of legal capacity,  who accesses the Platform for any purpose. A User may be a minor or a person without full  legal capacity, to the extent that he/she is represented by a legal representative. A user includes  any person for whom the user subscribes to the Services  

g) Hotline – telephone service of the Disciple  

h) Login – Disciples electronic mail address (e-mail address) indicated during the conclusion of  the agreement. The address is used for each access to the Profile;  

i) Terms and Conditions – the terms and conditions of the Service Provider, drawn up under the  provisions of the relevant laws  

j) Password – a string of characters used to gain authorized access to the Profile on the Platform  and used to identify the Disciple while providing Services, determined independently by the  person registering the Profile or the Disciple, or assigned automatically by the system during  profile registration, with the length of at least 8 characters, containing lowercase and uppercase  letters, digits or special characters;  

k) Platform – This progressive web app/website and its sub-domains or in the form of an  application for mobile devices, forming part of the ICT system, enabling the provision of  Platform Services;  

l) Profile – an individual and authorized Disciple’s account on the Platform;  

m) Service Provider/Provider - Great Commission Movement of Nigeria  

n) Services – Services provided based on the Terms and Conditions;  

3. GENERAL PROVISIONS 

3.1 The Terms and Conditions are made available free of charge on the website in a way that makes it  possible to obtain, reproduce and record their content.  

3.2 By accepting the Terms and Conditions, the User accepts the fact that the Services are provided mainly  through electronic communication and Physical communication  

3.3 These Terms and Conditions shall apply in the same way to discussions/agreements entered into by  the Users of the Platform.  

3.4 In matters not regulated herein, the provisions of universally applicable law shall apply.  3.5 The Service Provider is a not-for-profit, faith-based organization and has decided to provide this  service to connect Users to disciplers. Within the scope of services, the Service Provider may introduce  other services, carry out promotional activities or provide other information, under the generally  applicable regulations.   

4. REGISTRATION  

4.1 You may not register on the Platform if you are under 18 years of age (By using this platform or  agreeing to these general terms and conditions, you warrant and represent to us that you are at least  18 years of age)  

4.2 If you register for an account on the Platform, you will be asked to provide an email address/user ID  and password and you agree to:  

a. Keep your password confidential  

b. Notify us in writing immediately (using our contact details provided herein) if you become aware  of any disclosure of your password; and  

c. Be responsible for any activity on our platform arising from failure to keep your password  confidential and you may be held liable for any losses, claims, or damages arising from any such  failure  

d. Your account shall be used exclusively by you and you shall ON NO ACCOUNT transfer your  account to any third party  

e. We may suspend or cancel your account in the event of a breach of any of these terms and  conditions of use  

f. You may cancel your account on our Platform by contacting us.  

5. CONDITIONS FOR THE PROVISION OF SERVICES  

3.1 By accepting the Terms and Conditions, the User has access to tips for sharing the gospel of Jesus  Christ. The Disciple also has access to discipleship services  

3.2 The Disciple shall select a Discipler from the list made available on the Platform and which is  filtered based on the Disciple's location and discipleship needs  

3.3 A Disciple can rate a Discipler after the conclusion of a Discipleship session and the rating shall be  visible to all Users after a review of the rating has been done by us  

3.4  

6. PHYSICAL VISITS  

7. OWNERSHIP OF INTELLECTUAL PROPERTY  

All intellectual property including copyright, and trademarks. Materials available for use on the website  and so on are owned and controlled by us together with our licensors and shall not be used in any way  that infringes on our rights.  

8. DATA PRIVACY  

8.1 Users agree to the processing of their data under the terms of our Privacy Policy  8.2 We shall process all personal data obtained through the Platform and related services under the  terms of our Privacy Policy  

8.3 Disciplers shall be directly responsible to the Disciples for any misuse of their data and we shall  bear no liability in respect of any misuse by Disciplers of the Disciples' data   

9. CONCLUSION OF DISCIPLESHIP SERVICES  

9.1 The agreement concluded under the terms of these Terms and Conditions is an agreement for  knowledge sharing and peer-to-peer discipleship  

9.2 Concluding a Discipleship service  

a) The Agreement for the provision of the Discipleship Service is concluded at the moment:  i. Submission of the registration application and acceptance of the regulations, and terms  and conditions.  

ii. Request for a Discipler  

10. BREACHES OF THE TERMS AND CONDITIONS  

10.1 If we permit the registration of an account on our platform, it will remain open indefinitely subject  to these general terms and conditions  

10.2 If a User breaches these terms and conditions or if we reasonably suspect that you have breached  these general terms and conditions or any of our policies in any way, we may:  

a) Temporarily suspend your access to the Platform  

b) Permanently prohibit you from accessing the Platform  

c) Block computers using your IP address from accessing the Platform  

d) Suspend or delete your account on our Platform  

e) Commence legal action against you whether for breach of contract or otherwise  10.3 Where we suspend, prohibit, or block your access to our Platform or a part of our Platform you  must not take any action to circumvent such suspension or prohibition, or blocking (including  without limitation creating and/or using a different account).  

11. TECHNICAL REQUIREMENTS  

11.1  

11.2 The User shall be solely responsible for the non-performance or incorrect performance of the Service  resulting from the User’s failure to meet the requirements set out in the Terms and Conditions of the  Platform.  

12. RIGHTS AND OBLIGATIONS OF THE PARTIES  

12.1 We reserve the right to:  

1. temporary discontinuation of the provision of the Access Service, in particular, due to  maintenance activities or system modifications of the Platform,  

2. make available the data of Disciples required for the conduct of the service and their  availability calendars,  

3. promptly notify about Discipler’s unavailability resulting from circumstances that occurred  after the Disciple had selected the appointment  

13. LIMITATION AND EXCLUSIONS OF LIABILITY  

13.1 Nothing in these terms and conditions will:  

13.1.1 Limit any liabilities in any way that is not permitted under applicable law: or  

13.1.2 Exclude any liabilities or statutory rights that may not be excluded under applicable law  

13.2 The limitations and exclusion of liability set out in this section and elsewhere in these terms and  conditions:  

13.2.1 Are subject to section 13.1  

13.2.2 Govern all liabilities arising under terms and conditions or relating to the subject matter of  these general terms and conditions including liabilities arising in contract in tort (including  negligence) and for breach of statutory duty except to the extent expressly provided  otherwise in these general terms and conditions  

13.3 We will not be liable to you for any loss or damage of any nature including in respect of:  13.3.1 Any losses occasioned by any interruption or dysfunction to the website  13.3.2 Any losses arising out of any event or events beyond our reasonable control  13.3.3 Any loss or corruption of any data database or software; or  

13.3.4 Any special indirect or consequential loss or damage  

13.3.5 Any incomplete, untrue, or incorrect information provided by the Disciple, especially in the  case of third-party data provided without their knowledge or consent. The consequences of  providing incorrect, incomplete, untrue, misleading, or otherwise incorrect data shall be the  sole responsibility of the Disciple.  

13.3.6 The User’s use of the Platform in a manner contrary to the Terms and Conditions.  

13.4 We accept that we have an interest in limiting the personal liability of our officers and employees  and having regard to that interest you acknowledge that we are a not-for-profit entity; you agree  that you will not bring any claim personally against our officers or employees in respect of any  losses of any form which you suffer in connection with the Platform or these terms and conditions.  

13.5 The Discipler is not responsible for the Services provided by the Service Provider.  

14. COMPLAINTS  

1. The Disciple has the right to raise questions, comments, and complaints concerning the use  of the Services. Inquiries, comments, and complaints regarding the Services and the  operation of the Platform and related technical issues shall be submitted to:  

1. at the e-mail address  

2. at the hotline number,  

3. In writing to our mailing address.  

2. A complaint shall be considered as soon as possible in an electronic, written, or telephone  form, depending on the form in which the complaint was submitted.  

3. The content of the complaint should include at least:  

1. data allowing identification of the Disciple: Disciple’s login, first and last name, e mail address, and postal address (for complaints submitted by mail);  

2. specifying the subject of the complaint,   

3. Identify any requests made by the Disciple,  

4. Indication of the date of occurrence of an event proving the improper performance  of the Service.  

18. FINAL PROVISIONS  

1. These terms and conditions together with any of our policies constitute the entire  agreement between the User and us concerning the use of the Platform and shall supersede  previous agreements between the User and us concerning the use of the Platform  

2. Transmission of content that is unlawful, contrary to morality, or infringes our rights or  others, and which could cause or encourage behavior considered illegal, infringing the  rights of third parties, in particular copyright or personal rights, is prohibited.  

3. We are entitled to unilaterally amend the Terms and Conditions in case of occurrence:  1. circumstances of force majeure,  

2. changes to the applicable laws applicable to the provision of services by electronic  means or transactions concluded at a distance,  

3. Changes or introduction of new Services provided that the amendments to the  Terms and Conditions are aimed at adapting the content of the Terms and  Conditions to the offer.  

4. Any other reason that we deem fit  

5. We shall inform the Disciple of any changes to the Terms and Conditions immediately  after the Disciple logs on to the Platform. The Disciple shall be bound by the provisions of  the new Terms and Conditions where the Disciple continues usage of the Platform.  

6. We reserve the right to transfer the rights and obligations arising from the use of the  Platform to a third party that is related to us and fulfilling the requirements for the  provision of services covered by these Terms and Conditions, whereby the Disciple shall  be informed of the above immediately after logging on to the Platform by the Disciple. In  such a situation, the Disciple retains the right to terminate the Agreement with immediate  effect.  

7. If a provision of these terms and conditions ate held to be unenforceable or unlawful by  any court or other competent authority, the same shall be severed from this contract and  the other provisions will continue in effect  

8. No waiver of any breach of these terms and conditions shall be construed as a waiver of  any other breach of these terms and conditions  

19. LAW, JURISDICTION, AND DISPUTE RESOLUTION  

1. These terms and conditions shall be governed by and construed under the laws of the  Federal Republic of Nigeria.  

2. The Parties shall make an effort to settle all disputes amicably. Any dispute arising out of  these Terms of Use, which cannot be settled, by mutual agreement/negotiation within 1  (one) month shall be referred to a court of competent jurisdiction.  
` 